openapi: 3.0.3
info:
  title: 'Alternova API Documentation'
  version: 0.0.0
paths:
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/genre/:
    get:
      operationId: api_v1_genre_list
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Genre'
          description: ''
    post:
      operationId: api_v1_genre_create
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Genre'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Genre'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Genre'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
          description: ''
  /api/v1/genre/{id}/:
    get:
      operationId: api_v1_genre_retrieve
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this genre.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
          description: ''
    put:
      operationId: api_v1_genre_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this genre.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Genre'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Genre'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Genre'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
          description: ''
    patch:
      operationId: api_v1_genre_partial_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this genre.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedGenre'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedGenre'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedGenre'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
          description: ''
    delete:
      operationId: api_v1_genre_destroy
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this genre.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/stream/:
    get:
      operationId: api_v1_stream_list
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStreamList'
          description: ''
    post:
      operationId: api_v1_stream_create
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stream'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Stream'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Stream'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
          description: ''
  /api/v1/stream/{id}/:
    get:
      operationId: api_v1_stream_retrieve
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
          description: ''
    put:
      operationId: api_v1_stream_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Stream'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Stream'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Stream'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
          description: ''
    patch:
      operationId: api_v1_stream_partial_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedStream'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedStream'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedStream'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
          description: ''
    delete:
      operationId: api_v1_stream_destroy
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this stream.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1/stream/random_stream/:
    get:
      operationId: api_v1_stream_random_stream_retrieve
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stream'
          description: ''
  /api/v1/type/:
    get:
      operationId: api_v1_type_list
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Type'
          description: ''
    post:
      operationId: api_v1_type_create
      description: A simple ViewSet for viewing and editing accounts.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Type'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Type'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Type'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
  /api/v1/type/{id}/:
    get:
      operationId: api_v1_type_retrieve
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this type.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
    put:
      operationId: api_v1_type_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this type.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Type'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Type'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Type'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
    patch:
      operationId: api_v1_type_partial_update
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this type.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedType'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedType'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedType'
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Type'
          description: ''
    delete:
      operationId: api_v1_type_destroy
      description: A simple ViewSet for viewing and editing accounts.
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this type.
        required: true
      tags:
      - api
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    Genre:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
      required:
      - id
      - name
    PaginatedStreamList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Stream'
    PatchedGenre:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
    PatchedStream:
      type: object
      properties:
        name:
          type: string
          description: Register the name
          maxLength: 255
        genre:
          type: integer
          description: Select the genre
        type:
          type: integer
          description: Select the type
        views:
          type: integer
          readOnly: true
        score:
          type: string
          format: decimal
          nullable: true
    PatchedType:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
    Stream:
      type: object
      properties:
        name:
          type: string
          description: Register the name
          maxLength: 255
        genre:
          type: integer
          description: Select the genre
        type:
          type: integer
          description: Select the type
        views:
          type: integer
          readOnly: true
        score:
          type: string
          format: decimal
          nullable: true
      required:
      - genre
      - name
      - type
      - views
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    Type:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 255
      required:
      - id
      - name
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
