# Generated by Django 4.2.3 on 2023-07-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Register the name", max_length=255),
                ),
                ("views", models.BigIntegerField(default=0, editable=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=1, null=True
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        help_text="Select the genre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.genre",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="Select the type",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="streaming.type",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
