# Generated by Django 4.2.3 on 2023-07-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_genre_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
